[package]
name = "wenv"
version = "0.1.0"
edition = "2024"

[lints.clippy]
all = "deny"
pedantic = "warn"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "5"
notify = "8"
